GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/4

###
GET http://localhost:3001/api/persons/5c41c90e84d891c15dfa3431

###
GET http://localhost:3001/api/persons/6618d8b51ef6cef356d4fdb5
###
GET http://localhost:3001/api/persons/999

###
# Delete a person
DELETE http://localhost:3001/api/persons/61410

###
# Create a person
POST http://localhost:3001/api/persons HTTP/1.1s
Content-Type: application/json

{
    "name": "Test",
    "number": "10-1-4321"
}

###
PUT http://localhost:3001/api/persons/661916da630005e667945c83 HTTP/1.1s
Content-Type: application/json

{
    "name": "Test",
    "number": "10-1-1111"
}

###
GET http://localhost:3001